# $FreeBSD$

PORTNAME=	secadm
PORTVERSION=	0.2
CATEGORIES=	hardenedbsd

MAINTAINER=	shawn.webb@hardenedbsd.org
COMMENT=	HardenedBSD Security Administration

MASTER_SITES=	http://hardenedbsd.org/distfiles/

USES=	kmod
LIB_DEPENDS=	libucl.so:${PORTSDIR}/textproc/libucl

LIBDIR?=	${PREFIX}/lib

MAKE_JOBS_UNSAFE=	yes

.include <bsd.port.mk>

