# Created by: Shawn Webb <shawn.webb@hardenedbsd.org>
# $FreeBSD$

PORTNAME=	opnsense-update
PORTVERSION=	15.7.14
PORTREVISION=	0
CATEGORIES=	hardenedbsd

MAINTAINER=	shawn.webb@hardenedbsd.org
COMMENT=	Secadm rules for OPNSense+HardenedBSD

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	HardenedBSD
GH_COMMIT=	61d3d3e
GH_TAGNAME=	${GH_COMMIT}
GH_PROJECT=	opnsense-secadm-rules

.include <bsd.port.mk>
