# Created by: Franco Fichtner <franco@opnsense.org>
# $FreeBSD$

PORTNAME=	opnsense-update
PORTVERSION=	15.7.12
PORTREVISION=	0
CATEGORIES=	sysutils

MAINTAINER=	franco@opnsense.org
COMMENT=	OPNsense update utility

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	HardenedBSD
GH_PROJECT=	opnsense-update

.include <bsd.port.mk>
